export const REVIEWS = [
  { id: 1, initial: "م", name: "محمد عبدالله", city: "حي العليا", rating: 5, text: "جوارب ممتازة جداً. الجودة واضحة والملمس ناعم بجد. مريحة طول اليوم ولا تسبب ريحة.", date: "قبل 2 أيام", verified: true },
  { id: 2, initial: "س", name: "سارة خالد", city: "حي السليمانية", rating: 5, text: "خامتها روعة ومريحة جداً بالمشي. تغليف مرتب وتوصيل سريع وتجربة شراء بكل أمان.", date: "قبل 4 أيام", verified: true },
  { id: 3, initial: "ف", name: "فيصل عبدالرحمن", city: "حي الملقا", rating: 5, text: "أفضل شرابات جربتها للرياضة والمشاوير الطويلة. خذوا باقة التوفير أوفر بكثير.", date: "قبل 1 يوم", verified: true },
  { id: 4, initial: "ط", name: "طارق العلي", city: "حي الياسمين", rating: 5, text: "اللي يداوم ساعات طويلة، هذا المنتج له. مريحة وما تحس بالكتمة أبد. خدمة ممتازة.", date: "قبل 3 أيام", verified: true },
  { id: 5, initial: "أ", name: "أحمد سالم", city: "حي النرجس", rating: 5, text: "تستاهل كل ريال. جودة عالية فعلاً وما تتغير مع الغسيل.", date: "قبل 5 أيام", verified: true },
  { id: 6, initial: "ف", name: "فهد ناصر", city: "حي حطين", rating: 5, text: "مريحة جداً في اللبس وامتصاصها للعرق ممتاز. أنصح بها وبشدة.", date: "قبل 2 أيام", verified: true },
  { id: 7, initial: "ع", name: "عمر سعد", city: "حي العارض", rating: 5, text: "أفضل جوارب اشتريتها على الإطلاق. لا روائح ولا تعرق.", date: "قبل 6 أيام", verified: true },
  { id: 8, initial: "خ", name: "خالد يوسف", city: "حي القيروان", rating: 5, text: "القطن طبيعي وواضح من الملمس. الدوام صار أريح بكثير.", date: "قبل 1 يوم", verified: true },
  { id: 9, initial: "ن", name: "نورة سعود", city: "حي الربيع", rating: 5, text: "جودة تستحق الإشادة. توصيل سريع وتغليف احترافي.", date: "قبل 4 أيام", verified: true },
  { id: 10, initial: "ع", name: "عبدالعزيز فهد", city: "حي الغدير", rating: 5, text: "مريحة وما تضغط على القدم. شكراً لكم على هذا المنتج.", date: "قبل 7 أيام", verified: true },
  { id: 11, initial: "س", name: "سلطان وليد", city: "حي التعاون", rating: 5, text: "ثاني مرة أطلب منهم. الجودة ثابتة وممتازة.", date: "قبل 2 أيام", verified: true },
  { id: 12, initial: "س", name: "سعد محمد", city: "حي الازدهار", rating: 5, text: "منتج بطل بكل معنى الكلمة. انصحكم فيه.", date: "قبل 3 أيام", verified: true },
  { id: 13, initial: "ر", name: "ريان علي", city: "حي قرطبة", rating: 5, text: "سعر ممتاز مقابل الجودة. باقة التوفير خيار ذكي.", date: "قبل 5 أيام", verified: true },
  { id: 14, initial: "ع", name: "عبدالرحمن صالح", city: "حي غرناطة", rating: 5, text: "ريحتني كثير في المشي وما تسبب حساسية.", date: "قبل 1 يوم", verified: true },
  { id: 15, initial: "ت", name: "تركي نواف", city: "حي الشهداء", rating: 5, text: "منتج رائع وخدمة عملاء أروع. التوصيل كان في الموعد.", date: "قبل 6 أيام", verified: true },
  { id: 16, initial: "ع", name: "عبدالله ماجد", city: "حي الحمراء", rating: 5, text: "الجوارب ممتازة وما تنزلق مع الحركة. جودة عالية.", date: "قبل 2 أيام", verified: true },
  { id: 17, initial: "م", name: "مشاري طلال", city: "حي الخليج", rating: 5, text: "تجربة ممتازة وانصح بالشراء. الجودة لا يعلى عليها.", date: "قبل 4 أيام", verified: true },
  { id: 18, initial: "ف", name: "فراس حسن", city: "حي الروضة", rating: 5, text: "فعلاً تقنية النانو تفرق كثير. لا روائح بعد يوم طويل.", date: "قبل 3 أيام", verified: true },
  { id: 19, initial: "ب", name: "بدر سليمان", city: "حي القدس", rating: 5, text: "اشتريت باقة الـ 36 زوج وكفتني فترة طويلة. توفير حقيقي.", date: "قبل 7 أيام", verified: true },
  { id: 20, initial: "و", name: "وليد خالد", city: "حي النسيم", rating: 5, text: "خامة قوية وتعيش معك. غسيل ولبس وما تتغير.", date: "قبل 1 يوم", verified: true },
  { id: 21, initial: "ز", name: "زياد فهد", city: "حي السويدي", rating: 5, text: "اللون الأسود ما يبهت. القطن ممتاز وناعم.", date: "قبل 5 أيام", verified: true },
  { id: 22, initial: "ع", name: "عادل سامي", city: "حي الشفا", rating: 5, text: "مريحة جداً مع الأحذية الرياضية والرسمية.", date: "قبل 2 أيام", verified: true },
  { id: 23, initial: "ح", name: "حامد زيد", city: "حي طويق", rating: 5, text: "الافضل في السوق بلا منازع. شكراً متجر شرابي.", date: "قبل 4 أيام", verified: true },
  { id: 24, initial: "م", name: "ماجد عمر", city: "حي ظهرة لبن", rating: 5, text: "تخلصت من مشكلة تعرق القدمين بفضل هذه الجوارب.", date: "قبل 6 أيام", verified: true },
  { id: 25, initial: "ن", name: "نواف فيصل", city: "حي نمار", rating: 5, text: "المقاس ممتاز والالوان ثابتة. جودة رائعة.", date: "قبل 3 أيام", verified: true },
  { id: 26, initial: "ي", name: "ياسر طارق", city: "حي السفارات", rating: 5, text: "توصيل سريع جداً للمنزل. منتج يستحق التجربة.", date: "قبل 1 يوم", verified: true },
  { id: 27, initial: "ه", name: "هيثم جمال", city: "حي الواحة", rating: 5, text: "جوارب عملية جداً للاستخدام اليومي.", date: "قبل 7 أيام", verified: true },
  { id: 28, initial: "س", name: "سعود عبدالله", city: "حي إشبيلية", rating: 5, text: "صراحة مريحة بشكل ما توقعته. شكراً لكم.", date: "قبل 5 أيام", verified: true },
  { id: 29, initial: "م", name: "منصور راشد", city: "حي اليرموك", rating: 5, text: "منتج وطني بجودة عالمية. فخور جداً.", date: "قبل 2 أيام", verified: true },
  { id: 30, initial: "ص", name: "صالح علي", city: "حي المونسية", rating: 5, text: "انصح وبشدة. الجودة تتحدث عن نفسها.", date: "قبل 4 أيام", verified: true }
];
